
apiVersion: v1
kind: Service
metadata:
  name: pricepointscout-service
  namespace: {{ .Values.app.namespace }}
spec:
  selector:
    app: pricepointscout
  ports:
  - port: {{ .Values.app.service.port }}
    targetPort: {{ .Values.app.containerPort }}
    protocol: TCP
  type: ClusterIP
