apiVersion: v1
kind: Secret
metadata:
  name: pricepointscout-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  DATABASE_PASSWORD: {{ .Values.app.secret.databasePassword | b64enc }}  # Base64 encoded password
  JWT_SECRET: {{ .Values.app.secret.jwtSecret | b64enc }}  # Base64 encoded secret
  EMAIL_USERNAME: {{ .Values.app.secret.emailUsername | b64enc }}  # Base64 encoded email
  EMAIL_PASSWORD: {{ .Values.app.secret.emailPassword | b64enc }}  # Base64 encoded password