{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: {{ .Values.namespace }}
  labels:
    app: prometheus
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
  - name: web
    port: {{ .Values.prometheus.service.port }}
    targetPort: web
    protocol: TCP
  selector:
    app: prometheus
{{- end }}
