apiVersion: v2
name: pricepointscout-chart
description: A simple Helm chart for PricePointScout application
type: application
version: 0.1.0
appVersion: "1.0.0"
maintainers:
- email: contact@devopscube.com
  name: devopscube